# NUMPY : package for multidimensional array

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
np.ones((3,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.rand(3,2)

array([[0.28975948, 0.48619502],
       [0.32786804, 0.98893111],
       [0.22091732, 0.2983221 ]])

In [21]:
np.random.randn(3,2)

array([[-0.39183749, -0.41842822],
       [ 0.13075346, -0.60059284],
       [ 0.83761228,  1.39612556]])

In [22]:
np.random.randint(1,89)

30

In [23]:
np.random.randint(34,100,50)

array([63, 99, 87, 98, 98, 38, 39, 59, 81, 65, 60, 36, 92, 84, 45, 52, 82,
       52, 77, 87, 87, 85, 66, 65, 55, 99, 59, 86, 77, 82, 87, 40, 61, 90,
       37, 60, 78, 96, 92, 56, 39, 61, 58, 44, 47, 60, 50, 69, 90, 96])

In [24]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
rand_array=np.random.randint(0,100,20)
rand_array

array([16, 62, 29, 59, 66, 82, 92, 57, 65, 42,  8,  3, 73, 31, 62, 83, 75,
       95, 37, 97])

In [26]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
rand_array.min()

3

In [28]:
rand_array.argmin()

11

In [29]:
sample_array.dtype

dtype('int32')

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a=np.random.rand(2,3)
a

array([[0.98300766, 0.50920743, 0.28459755],
       [0.85196428, 0.55841693, 0.52761392]])

In [33]:
a.T

array([[0.98300766, 0.85196428],
       [0.50920743, 0.55841693],
       [0.28459755, 0.52761392]])

In [34]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
sample_array[3]

13

In [37]:
sample_array[3:7]

array([13, 14, 15, 16])

In [39]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [40]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
subset_sample_array=sample_array[0:7]

In [43]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [44]:
subset_sample_array[0:4]=79

In [45]:
subset_sample_array

array([79, 79, 79, 79, 14, 15, 16])

In [46]:
subset_sample_array[:]=748658

In [47]:
subset_sample_array

array([748658, 748658, 748658, 748658, 748658, 748658, 748658])

#Two-Dimensional Array

In [48]:
import numpy as np

In [50]:
sample_matrix=np.array([[1,2,3,4],[5,6,7,8],[9,0,10,11]])
sample_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 10, 11]])

In [54]:
sample_matrix[0:3,1]

array([2, 6, 0])

In [55]:
sample_matrix[2,:]

array([ 9,  0, 10, 11])

In [56]:
sample_matrix[2]

array([ 9,  0, 10, 11])

In [58]:
sample_matrix[:,2]

array([ 3,  7, 10])

In [59]:
sample_matrix[:,(3,2)]

array([[ 4,  3],
       [ 8,  7],
       [11, 10]])

In [61]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [62]:
sample_matrix+sample_matrix

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [63]:
np.exp(sample_matrix)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [64]:
np.sqrt(sample_matrix)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [65]:
np.max(sample_matrix)

19

In [66]:
np.log(sample_matrix)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [67]:
np.min(sample_matrix)

1

In [68]:
np.argmax(sample_matrix)

18

In [70]:
np.argmin(sample_matrix)

0

In [71]:
np.square(sample_matrix)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [72]:
np.std(sample_matrix)

5.477225575051661

In [73]:
np.mean(sample_matrix)

10.0

In [74]:
np.var(sample_matrix)

30.0

In [75]:
array=np.random.randn(3,4)
array

array([[ 1.68466117,  0.18395993, -1.7345526 ,  0.00314519],
       [-1.55144442,  0.93673443, -0.90275581,  0.51916884],
       [ 0.50024845, -0.02747744, -1.46936226, -0.4092142 ]])

In [76]:
np.round(array,decimals=3)

array([[ 1.685,  0.184, -1.735,  0.003],
       [-1.551,  0.937, -0.903,  0.519],
       [ 0.5  , -0.027, -1.469, -0.409]])

In [78]:
sports=(['golf','cricket','fball','cricket','fball','basketball','ball'])
np.unique(sports)

array(['ball', 'basketball', 'cricket', 'fball', 'golf'], dtype='<U10')